### ISSUE TITLE
Raise Exception for high masses

### ISSUE THREAD

**Issue by DoddyPhysics** [dgrin1/axionCAMB#1]
We should add a warning to appear if you choose m\gtrsim 1e-15 eV. 

Because we demand H(t_i)>>m then for m\gtrsim 1e-15 eV this implies H>H_{BBN} and there will be issues with entropy production from the changes in numbers of relativistic species that will affect the relic abundance and are not included in CAMB.

"Warning: you have chosen a high axion mass. Entropy production is not included, and may affect the relic abundance calculation."

**Comment by reneehlozek** [comment]
I've pushed a warning to the inidriver about this in the latest version.
