### ISSUE TITLE
Matter Power Spectrum Fault

### ISSUE THREAD

**Issue by Saber-of-QFT** [dgrin1/axionCAMB#11]
Hello, I met some weird problem when running axionCAMB.

I try to plot matter power spectrum with different axion mass or different axion fraction, to compare with Fig 2. in arXiv:1410.2896. I set parameter in params.ini as follow (for example, fixed f_ax = 1, and varying m_ax) :
![image](https://user-images.githubusercontent.com/44289053/172313662-8dccd1ed-b802-4f68-8c60-fc2ba62dd89d.png)

But I got some ridiculous result :
![image](https://user-images.githubusercontent.com/44289053/172313814-76f5ef8d-5059-4683-b2a2-4bed3690f31b.png)
![image](https://user-images.githubusercontent.com/44289053/172313848-5c649236-0b3e-48a4-9133-3d8081bf9921.png)

As I shown above, the power spectrum has an overall supression on all scales, where the large scale supression is unexpected.

But if I change the value of parameter 'omega_axion' as follow : 
![image](https://user-images.githubusercontent.com/44289053/172314625-fc640bb2-3ac0-4198-8832-c5e493469cf0.png)

I set the value of 'omega_axion' equal to 'omaxh2', which I think it is make no sense physically. But I obtain a result consistent with the Fig 2. in arXiv:1410.2896 : 
![image](https://user-images.githubusercontent.com/44289053/172315304-dfb7fc0a-e079-4a39-a8d9-9c4acc4ddc90.png)
![image](https://user-images.githubusercontent.com/44289053/172315350-774e8dc5-530d-4ccd-9b39-fcb9a948ffcb.png)

This result is very puzzling, have you met this problem before? Or did I set some cosmological parameters in a wrong way?

**Comment by dgrin1** [comment]
Hi there- is use physical units set to true or false? I think what is happening is that as you vary one parameter, the code is adjusting H_0 to hold something else fixed - this leads to (expected) changes in the growth function. That would explain why things act as expected when you vary the other parameter. You may have to switch the setting on physical_units flag and things should work then. Let me know what happens

**Comment by Saber-of-QFT** [comment]
Hi, in my original ini file, I set use_physical = F, because I want to use Omega_m, Omega_b, Omega_nu ... (and so no) as my input parameters. 

I try to set use_physical = T, and using ombh2, omch2, omnuh2 and omaxh2 as input parameters, then the result is right now. 

Does it mean if we want to include axion in our model, we have to set physical units to true ? Thank you !

**Comment by dgrin1** [comment]
I wouldn't put it that way - I would just say you have to properly interpret the results. If you set use_physical=false, the code will be adjusting H_0 in ways that dramatically alter the growth function - the results should be correct for that particular cosmology, its just that this may not be the cosmology you want to actually compute.

**Comment by Saber-of-QFT** [comment]
Understood. I will carefully setting parameters in my model. Thank you so much for helping!
